export type LayoutId =
  | 'L01_CLEAN'
  | 'L02_BRUTAL'
  | 'L03_LEDGER'
  | 'L04_STAMP'
  | 'L05_TERMINAL'
  | 'L06_RECEIPT'
  | 'L07_POSTER'
  | 'L08_MINIMAL'
  | 'L09_CARDSTACK'
  | 'L10_GRID'
  | 'L11_PULSE'
  | 'L12_MOTION'
  | 'L13_NEON'
  | 'L14_SUNSET'
  | 'L15_OCEAN'
  | 'L16_FOREST'
  | 'L17_MIDNIGHT'
  | 'L18_CORAL'
  | 'L19_STEEL'
  | 'L20_EMBER'
  | 'L21_FROST'
  | 'L22_LAVENDER'
  | 'L23_NOIR'
  | 'L24_MINT'
  | 'L25_COPPER'
  | 'L26_SLATE'
  | 'L27_CHERRY'
  | 'L28_ARCTIC'
  | 'L29_SAND'
  | 'L30_VOID'

export type LayoutSpec = {
  id: LayoutId
  name: string
  bg: string
  fg: string
  accent: string
  sub: string
  border: string
  radius: number
  hSize: number
  subSize: number
  metaSize: number
  showBigNumber: boolean
  showCauseChip: boolean
  showStamp: boolean
  showGrid: boolean
  showFooterBrand: boolean
  brutal: boolean
}

export const SHARE_CARD_LAYOUTS: LayoutSpec[] = [
  {
    id: 'L01_CLEAN',
    name: 'Clean Report',
    bg: '#0B0F19',
    fg: '#E8ECF6',
    accent: '#7C3AED',
    sub: '#B8C0D8',
    border: 'rgba(255,255,255,0.12)',
    radius: 28,
    hSize: 44,
    subSize: 18,
    metaSize: 14,
    showBigNumber: true,
    showCauseChip: true,
    showStamp: false,
    showGrid: false,
    showFooterBrand: true,
    brutal: false,
  },
  {
    id: 'L02_BRUTAL',
    name: 'Brutal Verdict',
    bg: '#070707',
    fg: '#F8F8F8',
    accent: '#F97316',
    sub: '#A3A3A3',
    border: 'rgba(255,255,255,0.14)',
    radius: 18,
    hSize: 48,
    subSize: 18,
    metaSize: 14,
    showBigNumber: true,
    showCauseChip: true,
    showStamp: true,
    showGrid: false,
    showFooterBrand: true,
    brutal: true,
  },
  {
    id: 'L03_LEDGER',
    name: 'Ledger Sheet',
    bg: '#0A0A0A',
    fg: '#EAEAEA',
    accent: '#22C55E',
    sub: '#9CA3AF',
    border: 'rgba(255,255,255,0.10)',
    radius: 24,
    hSize: 38,
    subSize: 16,
    metaSize: 13,
    showBigNumber: true,
    showCauseChip: false,
    showStamp: false,
    showGrid: true,
    showFooterBrand: true,
    brutal: false,
  },
  {
    id: 'L04_STAMP',
    name: 'Stamped Notice',
    bg: '#0B1220',
    fg: '#F1F5FF',
    accent: '#60A5FA',
    sub: '#B6C4E6',
    border: 'rgba(255,255,255,0.12)',
    radius: 30,
    hSize: 42,
    subSize: 18,
    metaSize: 13,
    showBigNumber: false,
    showCauseChip: true,
    showStamp: true,
    showGrid: false,
    showFooterBrand: true,
    brutal: false,
  },
  {
    id: 'L05_TERMINAL',
    name: 'Terminal Log',
    bg: '#06110B',
    fg: '#E7FFE8',
    accent: '#34D399',
    sub: '#9DE8B2',
    border: 'rgba(52,211,153,0.22)',
    radius: 20,
    hSize: 36,
    subSize: 16,
    metaSize: 13,
    showBigNumber: true,
    showCauseChip: false,
    showStamp: false,
    showGrid: true,
    showFooterBrand: true,
    brutal: true,
  },
  {
    id: 'L06_RECEIPT',
    name: 'Receipt',
    bg: '#0A0A0A',
    fg: '#F5F5F5',
    accent: '#FACC15',
    sub: '#D4D4D4',
    border: 'rgba(250,204,21,0.18)',
    radius: 16,
    hSize: 40,
    subSize: 16,
    metaSize: 12,
    showBigNumber: true,
    showCauseChip: true,
    showStamp: false,
    showGrid: true,
    showFooterBrand: true,
    brutal: false,
  },
  {
    id: 'L07_POSTER',
    name: 'Poster',
    bg: '#0B1020',
    fg: '#FFFFFF',
    accent: '#EC4899',
    sub: '#CBD5E1',
    border: 'rgba(236,72,153,0.20)',
    radius: 36,
    hSize: 50,
    subSize: 18,
    metaSize: 14,
    showBigNumber: false,
    showCauseChip: true,
    showStamp: false,
    showGrid: false,
    showFooterBrand: true,
    brutal: false,
  },
  {
    id: 'L08_MINIMAL',
    name: 'Minimal Calm',
    bg: '#0A0F1A',
    fg: '#EEF2FF',
    accent: '#A78BFA',
    sub: '#A5B4FC',
    border: 'rgba(255,255,255,0.08)',
    radius: 40,
    hSize: 40,
    subSize: 16,
    metaSize: 13,
    showBigNumber: false,
    showCauseChip: false,
    showStamp: false,
    showGrid: false,
    showFooterBrand: true,
    brutal: false,
  },
  {
    id: 'L09_CARDSTACK',
    name: 'Card Stack',
    bg: '#070A12',
    fg: '#E5E7EB',
    accent: '#38BDF8',
    sub: '#9CA3AF',
    border: 'rgba(56,189,248,0.18)',
    radius: 28,
    hSize: 40,
    subSize: 16,
    metaSize: 13,
    showBigNumber: true,
    showCauseChip: true,
    showStamp: false,
    showGrid: false,
    showFooterBrand: true,
    brutal: false,
  },
  {
    id: 'L10_GRID',
    name: 'Grid Report',
    bg: '#0B0B0B',
    fg: '#FAFAFA',
    accent: '#FB7185',
    sub: '#A3A3A3',
    border: 'rgba(255,255,255,0.12)',
    radius: 22,
    hSize: 38,
    subSize: 16,
    metaSize: 12,
    showBigNumber: true,
    showCauseChip: true,
    showStamp: false,
    showGrid: true,
    showFooterBrand: true,
    brutal: true,
  },
  {
    id: 'L11_PULSE',
    name: 'Pulse',
    bg: '#0A0D16',
    fg: '#F3F4F6',
    accent: '#22C55E',
    sub: '#9CA3AF',
    border: 'rgba(34,197,94,0.18)',
    radius: 30,
    hSize: 44,
    subSize: 18,
    metaSize: 13,
    showBigNumber: true,
    showCauseChip: false,
    showStamp: false,
    showGrid: false,
    showFooterBrand: true,
    brutal: false,
  },
  {
    id: 'L12_MOTION',
    name: 'Motion Stripe',
    bg: '#080A10',
    fg: '#F8FAFC',
    accent: '#7DD3FC',
    sub: '#CBD5E1',
    border: 'rgba(125,211,252,0.14)',
    radius: 34,
    hSize: 42,
    subSize: 17,
    metaSize: 13,
    showBigNumber: false,
    showCauseChip: true,
    showStamp: false,
    showGrid: true,
    showFooterBrand: true,
    brutal: false,
  },
  {
    id: 'L13_NEON',
    name: 'Neon Glow',
    bg: '#0A0012',
    fg: '#F0F0FF',
    accent: '#E879F9',
    sub: '#C4B5FD',
    border: 'rgba(232,121,249,0.25)',
    radius: 26,
    hSize: 46,
    subSize: 18,
    metaSize: 14,
    showBigNumber: true,
    showCauseChip: true,
    showStamp: false,
    showGrid: false,
    showFooterBrand: true,
    brutal: true,
  },
  {
    id: 'L14_SUNSET',
    name: 'Sunset Fade',
    bg: '#110A0A',
    fg: '#FFF5F5',
    accent: '#F97316',
    sub: '#FDBA74',
    border: 'rgba(249,115,22,0.20)',
    radius: 32,
    hSize: 44,
    subSize: 17,
    metaSize: 13,
    showBigNumber: true,
    showCauseChip: false,
    showStamp: false,
    showGrid: false,
    showFooterBrand: true,
    brutal: false,
  },
  {
    id: 'L15_OCEAN',
    name: 'Deep Ocean',
    bg: '#040A14',
    fg: '#E0F2FE',
    accent: '#0EA5E9',
    sub: '#7DD3FC',
    border: 'rgba(14,165,233,0.18)',
    radius: 28,
    hSize: 42,
    subSize: 16,
    metaSize: 13,
    showBigNumber: true,
    showCauseChip: true,
    showStamp: false,
    showGrid: true,
    showFooterBrand: true,
    brutal: false,
  },
  {
    id: 'L16_FOREST',
    name: 'Forest Night',
    bg: '#050B08',
    fg: '#ECFDF5',
    accent: '#10B981',
    sub: '#6EE7B7',
    border: 'rgba(16,185,129,0.16)',
    radius: 24,
    hSize: 40,
    subSize: 16,
    metaSize: 13,
    showBigNumber: false,
    showCauseChip: true,
    showStamp: true,
    showGrid: false,
    showFooterBrand: true,
    brutal: false,
  },
  {
    id: 'L17_MIDNIGHT',
    name: 'Midnight Blue',
    bg: '#030712',
    fg: '#F1F5F9',
    accent: '#6366F1',
    sub: '#A5B4FC',
    border: 'rgba(99,102,241,0.18)',
    radius: 30,
    hSize: 44,
    subSize: 18,
    metaSize: 14,
    showBigNumber: true,
    showCauseChip: true,
    showStamp: false,
    showGrid: false,
    showFooterBrand: true,
    brutal: false,
  },
  {
    id: 'L18_CORAL',
    name: 'Coral Reef',
    bg: '#0C0808',
    fg: '#FFF1F2',
    accent: '#FB7185',
    sub: '#FDA4AF',
    border: 'rgba(251,113,133,0.20)',
    radius: 36,
    hSize: 42,
    subSize: 17,
    metaSize: 13,
    showBigNumber: true,
    showCauseChip: false,
    showStamp: false,
    showGrid: false,
    showFooterBrand: true,
    brutal: false,
  },
  {
    id: 'L19_STEEL',
    name: 'Cold Steel',
    bg: '#08080A',
    fg: '#F4F4F5',
    accent: '#71717A',
    sub: '#A1A1AA',
    border: 'rgba(161,161,170,0.16)',
    radius: 20,
    hSize: 38,
    subSize: 16,
    metaSize: 12,
    showBigNumber: true,
    showCauseChip: true,
    showStamp: true,
    showGrid: true,
    showFooterBrand: true,
    brutal: true,
  },
  {
    id: 'L20_EMBER',
    name: 'Ember Dark',
    bg: '#0C0604',
    fg: '#FEF3C7',
    accent: '#D97706',
    sub: '#FCD34D',
    border: 'rgba(217,119,6,0.22)',
    radius: 22,
    hSize: 46,
    subSize: 18,
    metaSize: 14,
    showBigNumber: true,
    showCauseChip: true,
    showStamp: false,
    showGrid: false,
    showFooterBrand: true,
    brutal: true,
  },
  {
    id: 'L21_FROST',
    name: 'Arctic Frost',
    bg: '#0A0E14',
    fg: '#F0F9FF',
    accent: '#67E8F9',
    sub: '#A5F3FC',
    border: 'rgba(103,232,249,0.16)',
    radius: 38,
    hSize: 40,
    subSize: 16,
    metaSize: 13,
    showBigNumber: false,
    showCauseChip: false,
    showStamp: false,
    showGrid: false,
    showFooterBrand: true,
    brutal: false,
  },
  {
    id: 'L22_LAVENDER',
    name: 'Lavender Mist',
    bg: '#0C0A12',
    fg: '#FAF5FF',
    accent: '#C084FC',
    sub: '#D8B4FE',
    border: 'rgba(192,132,252,0.18)',
    radius: 34,
    hSize: 42,
    subSize: 17,
    metaSize: 13,
    showBigNumber: true,
    showCauseChip: true,
    showStamp: false,
    showGrid: false,
    showFooterBrand: true,
    brutal: false,
  },
  {
    id: 'L23_NOIR',
    name: 'Film Noir',
    bg: '#050505',
    fg: '#FAFAFA',
    accent: '#FFFFFF',
    sub: '#D4D4D4',
    border: 'rgba(255,255,255,0.10)',
    radius: 18,
    hSize: 48,
    subSize: 18,
    metaSize: 14,
    showBigNumber: true,
    showCauseChip: false,
    showStamp: true,
    showGrid: false,
    showFooterBrand: true,
    brutal: true,
  },
  {
    id: 'L24_MINT',
    name: 'Fresh Mint',
    bg: '#061210',
    fg: '#F0FDF4',
    accent: '#4ADE80',
    sub: '#86EFAC',
    border: 'rgba(74,222,128,0.16)',
    radius: 28,
    hSize: 40,
    subSize: 16,
    metaSize: 13,
    showBigNumber: true,
    showCauseChip: true,
    showStamp: false,
    showGrid: true,
    showFooterBrand: true,
    brutal: false,
  },
  {
    id: 'L25_COPPER',
    name: 'Copper Age',
    bg: '#0A0806',
    fg: '#FEF2E8',
    accent: '#EA580C',
    sub: '#FB923C',
    border: 'rgba(234,88,12,0.20)',
    radius: 24,
    hSize: 44,
    subSize: 17,
    metaSize: 13,
    showBigNumber: true,
    showCauseChip: true,
    showStamp: false,
    showGrid: false,
    showFooterBrand: true,
    brutal: false,
  },
  {
    id: 'L26_SLATE',
    name: 'Slate Board',
    bg: '#0F172A',
    fg: '#F8FAFC',
    accent: '#94A3B8',
    sub: '#CBD5E1',
    border: 'rgba(148,163,184,0.14)',
    radius: 20,
    hSize: 38,
    subSize: 16,
    metaSize: 12,
    showBigNumber: false,
    showCauseChip: true,
    showStamp: false,
    showGrid: true,
    showFooterBrand: true,
    brutal: false,
  },
  {
    id: 'L27_CHERRY',
    name: 'Cherry Blossom',
    bg: '#0A0608',
    fg: '#FFF5F7',
    accent: '#F472B6',
    sub: '#FBCFE8',
    border: 'rgba(244,114,182,0.18)',
    radius: 36,
    hSize: 44,
    subSize: 17,
    metaSize: 13,
    showBigNumber: true,
    showCauseChip: false,
    showStamp: false,
    showGrid: false,
    showFooterBrand: true,
    brutal: false,
  },
  {
    id: 'L28_ARCTIC',
    name: 'Arctic Night',
    bg: '#04080C',
    fg: '#F0FDFA',
    accent: '#2DD4BF',
    sub: '#5EEAD4',
    border: 'rgba(45,212,191,0.16)',
    radius: 30,
    hSize: 42,
    subSize: 16,
    metaSize: 13,
    showBigNumber: true,
    showCauseChip: true,
    showStamp: false,
    showGrid: false,
    showFooterBrand: true,
    brutal: false,
  },
  {
    id: 'L29_SAND',
    name: 'Desert Sand',
    bg: '#0C0A08',
    fg: '#FEFCE8',
    accent: '#EAB308',
    sub: '#FDE047',
    border: 'rgba(234,179,8,0.18)',
    radius: 26,
    hSize: 40,
    subSize: 16,
    metaSize: 13,
    showBigNumber: true,
    showCauseChip: true,
    showStamp: true,
    showGrid: false,
    showFooterBrand: true,
    brutal: false,
  },
  {
    id: 'L30_VOID',
    name: 'Void Black',
    bg: '#000000',
    fg: '#E5E5E5',
    accent: '#525252',
    sub: '#737373',
    border: 'rgba(82,82,82,0.20)',
    radius: 16,
    hSize: 50,
    subSize: 18,
    metaSize: 14,
    showBigNumber: true,
    showCauseChip: false,
    showStamp: true,
    showGrid: false,
    showFooterBrand: true,
    brutal: true,
  },
]

export function getLayout(id: LayoutId) {
  return SHARE_CARD_LAYOUTS.find(x => x.id === id) || SHARE_CARD_LAYOUTS[0]
}
